### ISSUE TITLE
(some) ICAO24 et al. from regional monitoring agencies

### ISSUE THREAD

**Issue by espinielli** [atmdata/atmdata#4]
For the list of RMAs (Regional Monitoring Agencies) see "States and designated RMAs" see
https://www.eurocontrol.int/service/european-regional-monitoring-agency

Some of them could be used to scrape hex, regno, ao; for example
https://www.eurocontrol.int/rmalive/operatorList.do

The [Middle East Monitoring Agency](https://midrma.com/en/home)'s Approvals page is well done and data seems easy to get:
* https://midrma.com/en/rvsm

Others have medieval sites and/or data (or no public access)

**Comment by xoolive** [comment]
included in the website
